version: '2'
networks:
  cachenet:
services:
  grima:
    image: "zemkat/grima:kubernetes"
    ports:
      - "19290:19290"
    environment:
      SESSION_MODULE: "redis"
      SESSION_PATH: "tcp://redis"
      DATABASE_URL: "pgsql:host=postgres;dbname=grima;user=grima;password=7ad0e257c0d00be2e4fbdc90ae97f7138fba124b42fb153628d58bbccfba3d87"
    networks:
      - cachenet
  redis:
    image: "redis:5.0"
    hostname: "redis"
    networks:
      - cachenet
  postgres:
    image: "postgres:12"
    hostname: "postgres"
    environment:
      POSTGRES_USER: grima
      POSTGRES_PASSWORD: 7ad0e257c0d00be2e4fbdc90ae97f7138fba124b42fb153628d58bbccfba3d87
      POSTGRES_DB: grima
    networks:
      - cachenet
